=== IgorPystovit/java_lab_spring/LabXML/src/main/resources/xmls/guns.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="guns">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gun" type="gunType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="gunType">
        <xs:sequence>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="handy" type="handyType"/>
            <xs:element name="origin" type="xs:string"/>
            <xs:element name="material" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="ttc" type="TTC"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TTC">
        <xs:sequence>
            <xs:element name="rangetype" type="rangeType"/>
            <xs:element name="range" type="xs:int"/>
            <xs:element name="sightseeingRange" type="xs:int"/>
            <xs:element name="clipped" type="xs:boolean"/>
            <xs:element name="optical" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

<!--    Availability enum-->
    <xs:simpleType name="availability" final="restriction">
        <xs:restriction>
            <xs:enumeration value="available"/>
            <xs:enumeration value="not available"/>
        </xs:restriction>
    </xs:simpleType>
<!--    RangeType enum-->
    <xs:simpleType name="rangeType" final="restriction">
        <xs:restriction>
            <xs:enumeration value="long"/>
            <xs:enumeration value="mid"/>
            <xs:enumeration value="low"/>
        </xs:restriction>
    </xs:simpleType>

<!--    Handy enum-->
    <xs:simpleType name="handyType" final="restriction">
        <xs:restriction>
            <xs:enumeration value="one_handed"/>
            <xs:enumeration value="two_handed"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== IgorPystovit/java_lab_spring/LabXML/src/main/resources/xmls/guns.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="guns.xsl"?>
<guns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="guns.xsd">
    <gun>
        <model>m-16</model>
        <handy>one_handed</handy>
        <origin>USA</origin>
        <material>plastic</material>
        <material>iron</material>
        <ttc>
            <rangetype>low</rangetype>
            <range>500</range>
            <sightseeingRange>900</sightseeingRange>
            <clipped>true</clipped>
            <optical>false</optical>
        </ttc>
    </gun>
    <gun>
        <model>MP5</model>
        <handy>two_handed</handy>
        <origin>Germany</origin>
        <material>iron</material>
        <ttc>
            <rangetype>low</rangetype>
            <range>100</range>
            <sightseeingRange>500</sightseeingRange>
            <clipped>true</clipped>
            <optical>false</optical>
        </ttc>
    </gun>
    <gun>
        <model>R8</model>
        <handy>two_handed</handy>
        <origin>Germany</origin>
        <material>wood</material>
        <material>iron</material>
        <ttc>
            <rangetype>long</rangetype>
            <range>1500</range>
            <sightseeingRange>2000</sightseeingRange>
            <clipped>false</clipped>
            <optical>true</optical>
        </ttc>
    </gun>
    <gun>
        <model>CZ-75</model>
        <handy>one_handed</handy>
        <origin>Czech</origin>
        <material>iron</material>
        <ttc>
            <rangetype>low</rangetype>
            <range>100</range>
            <sightseeingRange>300</sightseeingRange>
            <clipped>true</clipped>
            <optical>false</optical>
        </ttc>
    </gun>
</guns>
